//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_oborot
    {
        public int ID { get; set; }
        public Nullable<int> KL_KOD { get; set; }
        public Nullable<short> KOD_VAL { get; set; }
        public string RECEIPT_ACC { get; set; }
        public string COST_ACC { get; set; }
        public string QUANTITY { get; set; }
    }
}
