//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_risk
    {
        public int ID { get; set; }
        public Nullable<int> CR_KL_KOD { get; set; }
        public Nullable<short> CR_DL_KOD { get; set; }
        public string CR_KOM { get; set; }
        public Nullable<short> CR_RISK_LEVEL { get; set; }
        public Nullable<short> CR_OTV { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
