//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_paspdata
    {
        public int id { get; set; }
        public int kl_kod { get; set; }
        public byte dl_kod { get; set; }
        public string p_inn { get; set; }
        public string p_fam { get; set; }
        public string p_name { get; set; }
        public string p_otch { get; set; }
        public string p_grajd { get; set; }
        public string p_viddoksfr { get; set; }
        public string p_viddok { get; set; }
        public string p_srdok { get; set; }
        public string p_ndok { get; set; }
        public string p_mvd { get; set; }
        public Nullable<System.DateTime> p_enddok { get; set; }
        public Nullable<System.DateTime> p_datev { get; set; }
        public Nullable<bool> p_noend { get; set; }
        public string p_strb { get; set; }
        public string p_mb { get; set; }
        public Nullable<System.DateTime> p_db { get; set; }
        public Nullable<byte> p_pol { get; set; }
        public string p_father { get; set; }
        public string p_nation { get; set; }
        public Nullable<short> p_family_status { get; set; }
        public Nullable<int> vzml_dl_code { get; set; }
    }
}
