//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clients()
        {
            this.client_risk = new HashSet<client_risk>();
            this.ClientOrg = new HashSet<ClientOrg>();
            this.ClientOrg1 = new HashSet<ClientOrg>();
            this.LoanApplication = new HashSet<LoanApplication>();
            this.LoanContracts = new HashSet<LoanContracts>();
            this.LoanCredits = new HashSet<LoanCredits>();
            this.Guarantee = new HashSet<Guarantee>();
        }
    
        public int kl_kod { get; set; }
        public string kl_nam { get; set; }
        public string kl_nam_eng { get; set; }
        public Nullable<byte> kl_stat { get; set; }
        public Nullable<byte> kl_rzd { get; set; }
        public Nullable<bool> kl_rchp { get; set; }
        public Nullable<bool> kl_rpat { get; set; }
        public Nullable<bool> kl_rip { get; set; }
        public Nullable<byte> kl_opf { get; set; }
        public string kl_inn { get; set; }
        public Nullable<byte> kl_vidsob { get; set; }
        public Nullable<short> kl_otr { get; set; }
        public Nullable<short> kl_osnvd { get; set; }
        public string kl_kodter { get; set; }
        public Nullable<bool> kl_relig { get; set; }
        public Nullable<bool> kl_offsh { get; set; }
        public Nullable<int> kl_cfr { get; set; }
        public Nullable<bool> kl_benefs { get; set; }
        public string kl_benefsname { get; set; }
        public string kl_benefs_paspdata { get; set; }
        public string kl_tel1 { get; set; }
        public string kl_tel2 { get; set; }
        public string kl_tel3 { get; set; }
        public Nullable<byte> kl_orgreg { get; set; }
        public string kl_nomreg { get; set; }
        public string kl_okpo { get; set; }
        public string kl_rnsf { get; set; }
        public Nullable<System.DateTime> kl_datareg { get; set; }
        public Nullable<System.DateTime> kl_dataperereg { get; set; }
        public Nullable<System.DateTime> kl_dataendpat { get; set; }
        public string kl_ustav { get; set; }
        public string kl_wname { get; set; }
        public string kl_wfio { get; set; }
        public string kl_wdoljn { get; set; }
        public Nullable<bool> kl_sez { get; set; }
        public Nullable<System.DateTime> kl_sezend { get; set; }
        public Nullable<decimal> KL_BONUS { get; set; }
        public string kl_isys { get; set; }
        public Nullable<System.DateTime> kl_datecreate { get; set; }
        public Nullable<short> kl_otvcreate { get; set; }
        public string kl_keyw { get; set; }
        public Nullable<short> KODB { get; set; }
        public Nullable<short> KODC { get; set; }
        public Nullable<bool> kl_ins { get; set; }
        public Nullable<bool> kl_pzl { get; set; }
        public string kl_dopvd { get; set; }
        public Nullable<short> kl_goal { get; set; }
        public Nullable<bool> kl_fatca { get; set; }
        public Nullable<int> IdPatent { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<short> BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_risk> client_risk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrg> ClientOrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrg> ClientOrg1 { get; set; }
        public virtual clientPhoto clientPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanContracts> LoanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCredits> LoanCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guarantee> Guarantee { get; set; }
    }
}
