//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_dl
    {
        public int kl_kod { get; set; }
        public byte dl_kod { get; set; }
        public Nullable<bool> dl_relig { get; set; }
        public Nullable<bool> dl_offsh { get; set; }
        public Nullable<bool> dl_affinkod { get; set; }
        public Nullable<int> dl_cfr { get; set; }
        public Nullable<bool> dl_pzl { get; set; }
        public Nullable<byte> dl_dolgn { get; set; }
        public Nullable<byte> dl_rzd { get; set; }
        public string dl_tel1 { get; set; }
        public string dl_tel2 { get; set; }
        public string dl_tel3 { get; set; }
        public string dl_legal_doc { get; set; }
        public Nullable<System.DateTime> dl_enddov { get; set; }
        public Nullable<byte> dl_socst { get; set; }
        public Nullable<System.DateTime> dl_datecreate { get; set; }
        public Nullable<short> dl_otvcreate { get; set; }
        public Nullable<byte> dl_sortindx { get; set; }
        public string dl_client_bnfs { get; set; }
    }
}
