//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_comp_details
    {
        public int ID { get; set; }
        public Nullable<int> KL_KOD { get; set; }
        public string KL_ACTIV { get; set; }
        public string KL_CAPITAL { get; set; }
        public string KL_QUANTITY_W { get; set; }
        public string KL_QUANTITY_M { get; set; }
    }
}
