//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_adress
    {
        public int id { get; set; }
        public int kl_kod { get; set; }
        public byte dl_kod { get; set; }
        public string a_typeadress { get; set; }
        public string a_kstr { get; set; }
        public string a_knp { get; set; }
        public string a_np { get; set; }
        public string a_ind { get; set; }
        public string a_obl { get; set; }
        public string a_raion { get; set; }
        public string a_topfx { get; set; }
        public string a_to { get; set; }
        public string a_ulpfx { get; set; }
        public string a_ul { get; set; }
        public string a_dom { get; set; }
        public string a_korpuc { get; set; }
        public string a_ctroen { get; set; }
        public string a_kvart { get; set; }
    }
}
