//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientPhoto
    {
        public int KlCode { get; set; }
        public Nullable<byte> DlCode { get; set; }
        public byte[] PhotoBase64 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
