//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrg
    {
        public int Id { get; set; }
        public int OrgKlKod { get; set; }
        public int KlKod { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual clients clients1 { get; set; }
    }
}
