//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_licence
    {
        public int ID { get; set; }
        public Nullable<int> LCE_KL_KOD { get; set; }
        public string LCE_TYPE { get; set; }
        public string LCE_NUMBER { get; set; }
        public Nullable<System.DateTime> LCE_DATE_ISSUE { get; set; }
        public Nullable<System.DateTime> LCE_DATE_END { get; set; }
        public string LCE_ISSUED_BY { get; set; }
        public Nullable<bool> LCE_IsNoEnd { get; set; }
    }
}
