//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogkr
    {
        public int DG_POZN { get; set; }
        public Nullable<System.DateTime> DG_DATE { get; set; }
        public Nullable<System.DateTime> DG_DATE1 { get; set; }
        public Nullable<System.DateTime> DG_DATE2 { get; set; }
        public Nullable<System.DateTime> DG_DATEZ { get; set; }
        public string DG_NOM { get; set; }
        public string DG_NAM { get; set; }
        public string DG_KODV { get; set; }
        public Nullable<int> DG_KODKL { get; set; }
        public Nullable<int> DG_KODKL_OLD { get; set; }
        public Nullable<decimal> DG_SUM { get; set; }
        public Nullable<decimal> DG_SUM2 { get; set; }
        public Nullable<byte> DG_VIDOB { get; set; }
        public string DG_OPISOB { get; set; }
        public Nullable<byte> DG_VIDZ { get; set; }
        public Nullable<short> DG_SHKR { get; set; }
        public string DG_LC { get; set; }
        public string DG_LCD { get; set; }
        public string DG_LCPO { get; set; }
        public string DG_LCVS { get; set; }
        public string DG_LCRC { get; set; }
        public string DG_LCVSOC { get; set; }
        public Nullable<int> DG_CELKR { get; set; }
        public string DG_LCDEP { get; set; }
        public Nullable<int> DG_STAT { get; set; }
        public Nullable<byte> DG_KL { get; set; }
        public Nullable<byte> DG_VIDKR { get; set; }
        public Nullable<int> DG_STATUS { get; set; }
        public Nullable<byte> DG_GRPROC { get; set; }
        public string DG_KOM { get; set; }
        public string DG_KOM2 { get; set; }
        public Nullable<short> DG_VDNOMP { get; set; }
        public Nullable<decimal> DG_PSTP { get; set; }
        public Nullable<short> DG_OTV { get; set; }
        public Nullable<short> DG_VDNOM { get; set; }
        public Nullable<byte> DG_PLDAY { get; set; }
        public Nullable<byte> DG_PLFLPR1 { get; set; }
        public Nullable<System.DateTime> data_zal { get; set; }
        public string nom_zal { get; set; }
        public string nom_dov { get; set; }
        public Nullable<System.DateTime> data_dov { get; set; }
        public Nullable<System.DateTime> data_por { get; set; }
        public string nom_por { get; set; }
        public string passp_z { get; set; }
        public string passp_p { get; set; }
        public Nullable<decimal> crok { get; set; }
        public Nullable<System.DateTime> crok_do { get; set; }
        public Nullable<decimal> procent { get; set; }
        public Nullable<decimal> do_chislo { get; set; }
        public Nullable<decimal> shtraf { get; set; }
        public Nullable<decimal> comiss { get; set; }
        public Nullable<decimal> scomiss { get; set; }
        public string adress_z { get; set; }
        public string adress_p { get; set; }
        public string passp_z1 { get; set; }
        public string adress_z1 { get; set; }
        public string zalog1 { get; set; }
        public string zalog2 { get; set; }
        public string raion { get; set; }
        public string zdatel { get; set; }
        public Nullable<bool> c11 { get; set; }
        public Nullable<bool> c12 { get; set; }
        public Nullable<bool> c13 { get; set; }
        public Nullable<bool> c21 { get; set; }
        public Nullable<bool> c22 { get; set; }
        public Nullable<bool> c23 { get; set; }
        public Nullable<bool> c31 { get; set; }
        public Nullable<bool> c32 { get; set; }
        public Nullable<bool> c33 { get; set; }
        public Nullable<bool> c41 { get; set; }
        public Nullable<bool> c42 { get; set; }
        public Nullable<bool> c43 { get; set; }
        public string mecto_rab { get; set; }
        public string oform_zal { get; set; }
        public string telef_z { get; set; }
        public Nullable<int> notar { get; set; }
        public Nullable<int> cotr { get; set; }
        public Nullable<int> mec1 { get; set; }
        public Nullable<System.DateTime> data1 { get; set; }
        public Nullable<short> StatusRest1 { get; set; }
        public Nullable<int> mec2 { get; set; }
        public Nullable<System.DateTime> data2 { get; set; }
        public Nullable<short> StatusRest2 { get; set; }
        public Nullable<int> mec3 { get; set; }
        public Nullable<System.DateTime> data3 { get; set; }
        public Nullable<short> StatusRest3 { get; set; }
        public Nullable<int> mec4 { get; set; }
        public Nullable<System.DateTime> data4 { get; set; }
        public Nullable<short> StatusRest4 { get; set; }
        public Nullable<int> mec5 { get; set; }
        public Nullable<System.DateTime> data5 { get; set; }
        public Nullable<short> StatusRest5 { get; set; }
        public Nullable<int> mec6 { get; set; }
        public Nullable<System.DateTime> data6 { get; set; }
        public Nullable<short> StatusRest6 { get; set; }
        public Nullable<int> mec7 { get; set; }
        public Nullable<System.DateTime> data7 { get; set; }
        public Nullable<short> StatusRest7 { get; set; }
        public Nullable<decimal> ost { get; set; }
        public Nullable<int> DG_CHECK { get; set; }
        public string pas_prop { get; set; }
        public string pas_proj { get; set; }
        public string poruch { get; set; }
        public Nullable<System.DateTime> date_vn { get; set; }
        public Nullable<System.DateTime> date_stop { get; set; }
        public Nullable<int> DG_CHECKU { get; set; }
        public string DG_STATUS1 { get; set; }
        public Nullable<short> kodb { get; set; }
        public Nullable<int> kodc { get; set; }
        public Nullable<int> pr_old { get; set; }
        public Nullable<decimal> saldo_dox { get; set; }
        public Nullable<System.DateTime> date_nenach { get; set; }
        public Nullable<short> sotr { get; set; }
        public Nullable<short> affil { get; set; }
        public Nullable<short> DG_OTV1 { get; set; }
        public string poruch1 { get; set; }
        public string passp_p1 { get; set; }
        public string adress_p1 { get; set; }
        public string adress_pf { get; set; }
        public string adress_p1f { get; set; }
        public Nullable<short> pr_kr { get; set; }
        public string DG_OLDLC { get; set; }
        public string DG_OLDLCpo { get; set; }
        public Nullable<int> DG_OLDLcVs { get; set; }
        public Nullable<decimal> eps { get; set; }
        public Nullable<decimal> rasof { get; set; }
        public string naimgrup { get; set; }
        public Nullable<decimal> amortSt { get; set; }
        public Nullable<decimal> eps_as { get; set; }
        public Nullable<int> combine { get; set; }
        public Nullable<byte> ebrd { get; set; }
        public Nullable<byte> nbkr { get; set; }
        public Nullable<byte> dg_os { get; set; }
        public Nullable<byte> dg_obs { get; set; }
        public Nullable<byte> dg_sm { get; set; }
        public string auction { get; set; }
        public string zalogen { get; set; }
        public Nullable<int> pozn_old { get; set; }
        public string DG_LCVB { get; set; }
        public string DG_LCVBK { get; set; }
        public string DG_LCVND { get; set; }
        public Nullable<byte> DG_Class { get; set; }
        public Nullable<int> DG_Product { get; set; }
        public Nullable<decimal> DG_FirstPayment { get; set; }
        public Nullable<byte> DG_ID_Source { get; set; }
        public Nullable<short> DG_ID_Creator { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public Nullable<int> DgIdLc { get; set; }
        public Nullable<int> DgIdLcPo { get; set; }
        public Nullable<int> DgIdLcVn { get; set; }
        public Nullable<int> DgIdLcD { get; set; }
        public Nullable<int> DgIdLcVSOC { get; set; }
        public Nullable<int> DgIdLcOld { get; set; }
        public Nullable<int> DgIdLcPoOld { get; set; }
        public Nullable<int> DgIdLcDOld { get; set; }
        public Nullable<int> DgIdLcVSOCOld { get; set; }
        public Nullable<int> DgIdLcVB { get; set; }
        public Nullable<int> DgIdLcVK { get; set; }
        public Nullable<int> DgIdLcVND { get; set; }
        public int DgPozn { get; set; }
        public Nullable<bool> kl_rchp { get; set; }
        public Nullable<bool> kl_rip { get; set; }
        public Nullable<int> LC_VNFineOnMS { get; set; }
        public Nullable<int> LC_VNFineOnPercents { get; set; }
        public string LcVnShtrafMs { get; set; }
        public string LcVnShtrafPercents { get; set; }
        public string MlLcNsp { get; set; }
        public string MlLcVnNsp { get; set; }
    }
}
