//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENUMERATOR_SPR
    {
        public int id { get; set; }
        public int client_kod { get; set; }
        public int insider_kod { get; set; }
        public Nullable<int> korresp_kod { get; set; }
        public Nullable<int> reg_code { get; set; }
        public Nullable<int> biznes_partneru_code { get; set; }
        public Nullable<int> vzml_dl_code { get; set; }
        public Nullable<int> ms_id { get; set; }
        public Nullable<int> service_sms_id { get; set; }
        public Nullable<int> krProdId { get; set; }
    }
}
