//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guarantee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guarantee()
        {
            this.Guarantee_ProductsAndEquipment = new HashSet<Guarantee_ProductsAndEquipment>();
        }
    
        public int ID { get; set; }
        public int DG_POZN { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorID { get; set; }
        public int GuaranteeTypeID { get; set; }
        public Nullable<int> GuaranteeHolderID { get; set; }
        public Nullable<int> GuaranteeClientID { get; set; }
        public Nullable<int> GuaranteeOwnerType { get; set; }
        public string GuaranteeName { get; set; }
        public bool BorrowerIsHolder { get; set; }
        public Nullable<int> KindshipID { get; set; }
    
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guarantee_ProductsAndEquipment> Guarantee_ProductsAndEquipment { get; set; }
    }
}
