//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class kalendar
    {
        public System.DateTime K_DATE { get; set; }
        public Nullable<byte> K_PRIZ { get; set; }
        public Nullable<bool> IsNbkrWorkDay { get; set; }
    }
}
