//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient_p482_spr
    {
        public int id { get; set; }
        public Nullable<int> kod { get; set; }
        public Nullable<int> parent { get; set; }
        public string p482 { get; set; }
        public Nullable<byte> podoz { get; set; }
        public Nullable<bool> license { get; set; }
        public Nullable<byte> risk { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
