//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int ID { get; set; }
        public string ApplicationNumber { get; set; }
        public short BranchID { get; set; }
        public short OfficeID { get; set; }
        public short CurrencyID { get; set; }
        public int ClientID { get; set; }
        public decimal Amount { get; set; }
        public decimal LoanPercent { get; set; }
        public int PeriodInMonth { get; set; }
        public string GroupName { get; set; }
        public decimal FirstPaymentInPercent { get; set; }
        public byte AttractionCanalID { get; set; }
        public int ProductID { get; set; }
        public byte ClientClassID { get; set; }
        public byte TypeClientID { get; set; }
        public int AuctionSourceID { get; set; }
        public Nullable<byte> PurposeID { get; set; }
        public byte PaymentSourceID { get; set; }
        public int GuaranteeID { get; set; }
        public byte StatusID { get; set; }
        public short TypeCreditID { get; set; }
        public int EnterpriseID { get; set; }
        public byte LoanSubTypeID { get; set; }
        public int AimsID { get; set; }
        public string AimsComment { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime FirstContactDate { get; set; }
        public Nullable<System.DateTime> AnalysisDate { get; set; }
        public Nullable<System.DateTime> CommitteeDate { get; set; }
        public decimal PersonID { get; set; }
        public short CreatorID { get; set; }
        public string BankConnection { get; set; }
        public string Comment { get; set; }
        public string ClientComment { get; set; }
        public Nullable<byte> PercentType { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
