//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanGraphSettings
    {
        public int DgPozn { get; set; }
        public int KlKode { get; set; }
        public System.DateTime DateStart { get; set; }
        public int RepayType { get; set; }
        public int PrivelegPeriodMS { get; set; }
        public int PrivelegPeriodPercent { get; set; }
        public bool FiveDayPrincip { get; set; }
        public bool IssueCondition { get; set; }
        public System.DateTime ActualGraphDate { get; set; }
        public int ActualGraphNum { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int OtvNum { get; set; }
        public int GraphType { get; set; }
        public decimal Sum { get; set; }
        public int MonthCount { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
