//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPercent
    {
        public int DgPozn { get; set; }
        public int KodKl { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public decimal Percents { get; set; }
        public decimal FinePercent { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Irr { get; set; }
        public Nullable<decimal> AmortizationValue { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
