//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanCredits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanCredits()
        {
            this.LoanGraph = new HashSet<LoanGraph>();
        }
    
        public int DgPozn { get; set; }
        public int KodKl { get; set; }
        public int Pozn_Old { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> SourceID { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public byte QuantityID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> FirstPayment { get; set; }
        public decimal Amount { get; set; }
        public short TypeCreditID { get; set; }
        public int EnterpriseID { get; set; }
        public Nullable<int> AimsID { get; set; }
        public Nullable<byte> PurposeID { get; set; }
        public Nullable<byte> StatusCreditID { get; set; }
        public Nullable<short> LenderID { get; set; }
        public Nullable<short> ResponsibleID { get; set; }
        public Nullable<short> CreatorID { get; set; }
        public Nullable<System.DateTime> DateFactEnd { get; set; }
        public Nullable<byte> StatusEnd { get; set; }
        public Nullable<byte> TypeEnd { get; set; }
        public Nullable<decimal> AmountEnd { get; set; }
        public Nullable<short> CheckCredits { get; set; }
    
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanGraph> LoanGraph { get; set; }
        public virtual sprotv sprotv { get; set; }
    }
}
