//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanIssue
    {
        public int DgPozn { get; set; }
        public int KodKl { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> Kodb { get; set; }
        public Nullable<int> Kodc { get; set; }
        public Nullable<int> LC_Loan { get; set; }
        public Nullable<int> LC_Discount { get; set; }
        public Nullable<int> LC_Income { get; set; }
        public Nullable<int> LC_Insurance { get; set; }
        public Nullable<int> LC_Delivery { get; set; }
        public Nullable<decimal> AmountCommision { get; set; }
        public Nullable<decimal> AmountInsurance { get; set; }
        public Nullable<int> Otv { get; set; }
        public Nullable<bool> Cash { get; set; }
        public Nullable<bool> HisOffice { get; set; }
        public Nullable<int> DeliveryKodb { get; set; }
        public Nullable<int> DeliveryKodc { get; set; }
        public Nullable<int> DO_POZN { get; set; }
    }
}
