//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanGraph
    {
        public int DgPozn { get; set; }
        public int KlKode { get; set; }
        public System.DateTime Date { get; set; }
        public int PayoutNumber { get; set; }
        public decimal Issue { get; set; }
        public decimal RemainderMS { get; set; }
        public decimal RepaymentMS { get; set; }
        public decimal RepaymentPercent { get; set; }
        public decimal RepaymentMSPer { get; set; }
        public Nullable<decimal> RepaymentNsp { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int HistoryNum { get; set; }
        public int OtvNum { get; set; }
        public Nullable<decimal> GrSumPp1 { get; set; }
        public Nullable<decimal> GrSumPp2 { get; set; }
        public Nullable<decimal> PercentSumEpc { get; set; }
        public Nullable<decimal> AmortizationSumEndPeriod { get; set; }
        public Nullable<decimal> AmortizationSum { get; set; }
        public Nullable<decimal> OperSum { get; set; }
    
        public virtual LoanCredits LoanCredits { get; set; }
    }
}
