//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_APP
    {
        public int id { get; set; }
        public Nullable<int> formNum { get; set; }
        public string errorMsg { get; set; }
        public string innerMsg { get; set; }
        public string method { get; set; }
        public Nullable<System.DateTime> dateLog { get; set; }
        public string ip { get; set; }
        public string AppName { get; set; }
    }
}
