//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ow
    {
        public int id { get; set; }
        public Nullable<int> ow_modul { get; set; }
        public Nullable<int> ow_type { get; set; }
        public Nullable<int> ow_operation_id { get; set; }
        public Nullable<int> ow_object_id { get; set; }
        public string ow_name { get; set; }
        public Nullable<int> ow_otv_oper { get; set; }
        public Nullable<int> ow_compl { get; set; }
        public Nullable<int> ow_check { get; set; }
        public Nullable<System.DateTime> ow_date_time { get; set; }
        public Nullable<System.DateTime> ow_s_date { get; set; }
        public string ow_text { get; set; }
        public Nullable<int> ow_edit { get; set; }
        public Nullable<int> ow_open { get; set; }
    }
}
