//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class rekvizit
    {
        public int ID { get; set; }
        public short KODB { get; set; }
        public short KODC { get; set; }
        public string rv_npunkt { get; set; }
        public string rv_podrazd { get; set; }
        public string rv_fio { get; set; }
        public string rv_doljn { get; set; }
        public string rv_doljn_rp { get; set; }
        public string rv_doljn_fio_rp { get; set; }
        public string rv_dok { get; set; }
        public string rv_fio2 { get; set; }
        public string rv_doljn2 { get; set; }
        public string rv_doljn_rp2 { get; set; }
        public string rv_doljn_fio_rp2 { get; set; }
        public string rv_dok2 { get; set; }
        public string rv_fio3 { get; set; }
        public string rv_doljn3 { get; set; }
        public string rv_doljn_rp3 { get; set; }
        public string rv_doljn_fio_rp3 { get; set; }
        public string rv_dok3 { get; set; }
        public string rv_adr { get; set; }
        public string rv_rekvizit { get; set; }
        public string rv_rekvizit2 { get; set; }
        public string rv_rekvizit3 { get; set; }
        public string rv_dop1 { get; set; }
        public string rv_dop2 { get; set; }
        public string rv_dop3 { get; set; }
        public string rv_podrazd_ru { get; set; }
        public string rv_podrazd_eng { get; set; }
        public string rv_podrazd_kg { get; set; }
        public string rv_doljn_ru { get; set; }
        public string rv_doljn_eng { get; set; }
        public string rv_doljn_kg { get; set; }
        public string rv_fio_ru { get; set; }
        public string rv_fio_eng { get; set; }
        public string rv_fio_kg { get; set; }
        public string rv_doljn_ca_ru { get; set; }
        public string rv_doljn_ca_eng { get; set; }
        public string rv_doljn_ca_kg { get; set; }
        public string rv_fio_ca_ru { get; set; }
        public string rv_fio_ca_eng { get; set; }
        public string rv_fio_ca_kg { get; set; }
        public string rv_npunkt_kg { get; set; }
        public string rv_doljn2_kg { get; set; }
        public string rv_rekvizit_kg { get; set; }
        public string rv_dok_kg { get; set; }
        public string rv_dok2_kg { get; set; }
        public string rvPosition5 { get; set; }
        public string rvPosition5Rp { get; set; }
        public string rvPosition5Fio { get; set; }
        public string rvPosition5FioRp { get; set; }
        public Nullable<bool> rvIsEnablePosition5 { get; set; }
        public string rvPosition5DocNumber { get; set; }
    }
}
