//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class spr
    {
        public int id { get; set; }
        public byte s_tip { get; set; }
        public int s_kod { get; set; }
        public string s_nam { get; set; }
        public string s_kodnew { get; set; }
    }
}
