//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprotv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sprotv()
        {
            this.LoanApplication = new HashSet<LoanApplication>();
            this.LoanCredits = new HashSet<LoanCredits>();
        }
    
        public short OT_NOM { get; set; }
        public Nullable<short> OT_SHKOD { get; set; }
        public string OT_ISYS { get; set; }
        public string OT_UID { get; set; }
        public string OtPassword { get; set; }
        public Nullable<bool> LOCKED { get; set; }
        public string OT_FIO { get; set; }
        public string OT_NAME { get; set; }
        public Nullable<short> OT_LEVEL { get; set; }
        public Nullable<int> OT_OTD { get; set; }
        public Nullable<int> OT_PODRAZD { get; set; }
        public Nullable<short> OT_OTVHEADER { get; set; }
        public Nullable<short> kodb_in { get; set; }
        public Nullable<short> kodc_in { get; set; }
        public Nullable<bool> combo_fil { get; set; }
        public Nullable<bool> combo_fil2 { get; set; }
        public Nullable<bool> combo_kas { get; set; }
        public Nullable<bool> MSoffice { get; set; }
        public Nullable<short> OT_SHKODV { get; set; }
        public Nullable<bool> filial_all { get; set; }
        public Nullable<bool> filial_all2 { get; set; }
        public Nullable<bool> spec_log { get; set; }
        public Nullable<System.DateTime> OT_DATEREG { get; set; }
        public string OT_PASW { get; set; }
        public Nullable<System.DateTime> OT_DATECHPWD { get; set; }
        public Nullable<short> OT_LEVELK { get; set; }
        public Nullable<int> OT_PN { get; set; }
        public Nullable<short> OT_SHKODK { get; set; }
        public string telOtv { get; set; }
        public Nullable<bool> IsAccessYourDoc { get; set; }
        public Nullable<bool> IsFirstEnter { get; set; }
        public Nullable<bool> IsCheckRequest { get; set; }
        public Nullable<bool> IsSqlAuth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCredits> LoanCredits { get; set; }
    }
}
