//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGuarantee
    {
        public Nullable<long> RowNumber { get; set; }
        public int ID { get; set; }
        public int DG_POZN { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorID { get; set; }
        public int GuaranteeTypeID { get; set; }
        public string GtName { get; set; }
        public Nullable<int> GuaranteeHolderID { get; set; }
        public Nullable<int> GuaranteeClientID { get; set; }
        public Nullable<int> GuaranteeOwnerType { get; set; }
        public string GuaranteeName { get; set; }
        public string GuaranteeHolderName { get; set; }
    }
}
