//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficWaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLoanContract
    {
        public int DG_POZN { get; set; }
        public System.DateTime DG_DATE { get; set; }
        public Nullable<System.DateTime> DG_DATEZ { get; set; }
        public string DG_KODV { get; set; }
        public string DG_NOM { get; set; }
        public string DG_NAM { get; set; }
        public decimal DG_SUM { get; set; }
        public int dg_nomco { get; set; }
        public Nullable<short> kodb { get; set; }
        public int kodc { get; set; }
        public string DG_LC { get; set; }
        public Nullable<decimal> ML_OSTV2 { get; set; }
        public Nullable<decimal> ML_OSTN2 { get; set; }
        public string GroupName { get; set; }
        public byte DG_VIDKR { get; set; }
        public int DG_KODKL { get; set; }
        public Nullable<short> DG_OTV { get; set; }
        public Nullable<short> DG_OTV1 { get; set; }
        public Nullable<short> DG_CreatorID { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public int DgPoznOld { get; set; }
    }
}
